name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build Developement/Front-end/click-trip --file Developement/Front-end/click-trip/Dockerfile --tag my-react-app:${{ github.sha }}

